name: PHP Composer CI

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Adjust the PHP version as needed

      - name: Install phpspreadsheet
        run: composer require phpoffice/phpspreadsheet

      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: phpspreadsheet-files
          path: path/to/phpspreadsheet  # Adjust the path to where the files are located
